### ISSUE TITLE
No login

### ISSUE THREAD

**Issue by lroura** [icodethings/netbank-js#1]
Hi
I tried to do a login but, in NetBank.js:45 the code thow an error, because the body in the respond is an empty string, so JSON.parse() thows an error
![untitled](https://cloud.githubusercontent.com/assets/27731897/25492274/8a588b9c-2b40-11e7-8bd2-d4451ed7913b.png)
What should I do in this case?

**Comment by sebszocinski** [comment]
Same error here, any updates on this @icodethings?

**Comment by icodethings** [comment]
@lroura @sebszocinski Looks like netbank has retired the mobile ajax site I was using. Sorry!
